server:
  port: 8000
  servlet:
    context-path: /code-generator
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #    MySQL配置
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://123.57.217.240:3306/nacos_config?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
    #oracle配置
    #    driverClassName: oracle.jdbc.OracleDriver
    #    url: jdbc:oracle:thin:@localhost:1521:orcl
    #    username: app
    #    password: jq123
    #PostgreSQL配置
    #    driverClassName: org.postgresql.Driver
    #    url: jdbc:postgresql://123.57.217.240:5432/emm_manager
    #    username: root
    #    password: 123456
    #SQLServer配置
    #    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    #    url: jdbc:sqlserver://192.168.10.10:1433;DatabaseName=renren_fast
    #    username: sa
    #    password: 123456
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  resources:
    static-locations: classpath:/static/,classpath:/views/
mybatis:
  mapperLocations: classpath:mapper/**/*.xml
pagehelper:
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
#mongodb:
#  host: localhost
#  port: 27017
#  auth: false #是否使用密码验证
#  username: root
#  password: 123456
#  source: 123456
#  database: test
#指定数据库，可选值有【mysql、oracle、sqlserver、postgresql】
generator:
  database: mysql